columns_to_use = [
	"m_mumu",
	"phi_CS",
	"j2_btagPNetQvG",
	"minDeltaEta",
	"mu1_eta",
	"y_mumu",
	"j1_eta",
	"m_jj",
	"delta_eta_jj",
	"R_pt",
	"j1_btagPNetQvG",
	"mu1_pt",
	"phi_mumu",
	"minDeltaPhi",
	"pt_mumu",
	"pt_jj",
	"pt_centrality",
	"j2_pt",
	"mu2_pt",
	"eta_mumu",
	"j2_eta",
	"cosTheta_CS",
	"mu2_eta",
	"dR_mumu",
	"j1_pt",
	"Zepperfield_Var"
]

selection_column = "VBF_JetVeto"

signal_event_types = [31]

valid_size = 0.15
test_size = 0.40

output_directory = "/afs/cern.ch/user/a/ayeagle/H_mumu/Studies/DNN/preprocessing"
dataset_directory = "/afs/cern.ch/user/a/ayeagle/H_mumu/Studies/DNN/datasets"
run_name = "set_run_1"
