
columns_config = {
    "metadata" : [
        "FullEventId",
        "isData",
        #"weight_MC_Lumi_pu",
        "final_weight",
        "era",
        "process",
        "dataset",
        "baseline_muonJet",
        "Signal_Fit",
        "Signal_ext",
        "H_sideband",
        "Z_sideband",
        "VBF",
        "VBF_JetVeto"
    ],
    "flat_vars" : [
        'mu1_eta',
        'mu1_pt',
        'mu2_eta',
        'mu2_pt',
        'dR_mumu',
        'm_mumu',
        'eta_mumu',
        'cosTheta_CS',
        'phi_mumu',
        'pt_mumu',
        'y_mumu',
        'phi_CS',
        # 'R_pt',
        # 'minDeltaEtaSigned',
        # 'minDeltaPhi',
        # 'Zepperfield_Var',
        # 'pt_centrality',
        # 'j1_eta',
        # 'j1_pt',
        # 'j1_btagPNetQvG',
        # 'j2_eta',
        # 'j2_pt',
        # 'j2_btagPNetQvG',
        # 'm_jj',
        # 'delta_eta_jj',
        # 'pt_jj',
        'nJet',
        'nSoftActivityJet',
        'SoftActivityJetHT',
        'SoftActivityJetHT2',
        'SoftActivityJetHT5',
        'SoftActivityJetHT10',
        'SoftActivityJetNjets2',
        'SoftActivityJetNjets5',
        'SoftActivityJetNjets10'
    ],
    "jet_vars" : [
        'FilteredJet_pt',
        'FilteredJet_eta',
        'FilteredJet_phi',
        #'FilteredJet_btagPNetB',
        #'FilteredJet_btagPNetCvB',
        #'FilteredJet_btagPNetCvL',
        #'FilteredJet_btagPNetCvNotB',
        #'FilteredJet_btagPNetQvG',
        #'FilteredJet_btagPNetTauVJet'
    ]
}