############## TT ##############
TT:
  name: "t#bar{t}"
  color: "kGreen-3"  # eliminates need for plot.yaml
  color_mplhep: darkblue  # turquoise
  datasets:
    - TTto2L2Nu
    - TTtoLNu2Q
    - TTto4Q

TT_Inclusive:
  name: "t#bar{t} Inclusive"
  color: "kGreen-3"
  color_mplhep: darkblue  # turquoise
  datasets:
    - TT

############## DY ##############
# DY:
#   name: "DY M50"
#   # cross_section_correction: 12/ 11  # NLO -> NNLO
#   color: kAzure-9
#   color_mplhep: lightskyblue
#   datasets:
#     - DYto2E_M_50_amcatnloFXFX
#     - DYto2E_M_50_amcatnloFXFX_ext1
#     - DYto2Mu_M_50_amcatnloFXFX
#     - DYto2Mu_M_50_amcatnloFXFX_ext1

DY:
  name: "DY M50"
  cross_section_correction: 12/ 11  # NLO -> NNLO
  color: "kAzure+7"
  color_mplhep: lightskyblue
  datasets:
    - DYto2E_M_50_0J_amcatnloFXFX
    - DYto2Mu_M_50_0J_amcatnloFXFX
    - DYto2Tau_M_50_0J_amcatnloFXFX
    - DYto2E_M_50_1J_amcatnloFXFX
    - DYto2Mu_M_50_1J_amcatnloFXFX
    - DYto2Tau_M_50_1J_amcatnloFXFX
    - DYto2E_M_50_2J_amcatnloFXFX
    - DYto2Mu_M_50_2J_amcatnloFXFX
    - DYto2Tau_M_50_2J_amcatnloFXFX

DYToMuMu_amcatnloFXFX:
  name: "DY M50"
  # cross_section_correction: 12/ 11  # NLO -> NNLO
  color: kAzure-9
  color_mplhep: lightskyblue
  datasets:
    - DYto2Mu_M_50_amcatnloFXFX
    - DYto2Mu_M_50_amcatnloFXFX_ext1


############## WJetsToLNu ##############
W:
  name: "W"
  color: "kGreen"  # eliminates need for plot.yaml
  color_mplhep: yellow
  datasets:
    - WtoLNu_amcatnloFXFX

W_NJets:
  name: "W"
  color: "kGreen"  # eliminates need for plot.yaml
  color_mplhep: yellow
  datasets:
    - WtoLNu_0J_amcatnloFXFX
    - WtoLNu_1J_amcatnloFXFX
    - WtoLNu_2J_amcatnloFXFX


EWK:
  name: "EWK"
  color: kMagenta+3
  color_mplhep: darkmagenta
  datasets:
    - EWK_2L2J_madgraph_herwig


############## Other single H  ##############
H_mainBckg:
  name: "Single H"
  color: kPink
  color_mplhep: darkgreen
  datasets:
    - GluGluHto2Tau_M125
    - GluGluHto2B_M125
    - VBFHto2B_M125
    - VBFHto2Tau_UncorrelatedDecay_UnFiltered
    - VBFHto2Tau_UncorrelatedDecay_Filtered
    - GluGluHto2Wto2L2Nu_M125

############## VV ##############
VV_Inclusive:
  name: "VV Inclusive"
  color: kPink+2
  color_mplhep: mistyrose
  datasets:
    - WW
    - WZ
    - ZZ

VV:
  name: "VV"
  color: kPink+2
  color_mplhep: mistyrose
  datasets:
    - WWto2L2Nu_powheg
    - WWto4Q_powheg
    - WWtoLNu2Q_powheg
    - WZto3LNu_powheg
    - WZto2L2Q_powheg
    - WZtoLNu2Q_powheg
    - ZZto2L2Nu_powheg
    - ZZto2L2Q_powheg
    - ZZto2Nu2Q_powheg
    - ZZto4L_powheg

############## VH non-inclusive ##############
VH_inclusive:
  name: "VH"
  color: kPink+2
  color_mplhep: tan
  datasets:
    - ZH_Hto2B_Zto2L
    - ZH_Hto2B_Zto2Q
    - ggZH_Hto2B_Zto2L
    - ggZH_Hto2B_Zto2Q
    - WminusH_Hto2B_Wto2Q
    - WminusH_Hto2B_WtoLNu
    - WplusH_Hto2B_Wto2Q
    - WplusH_Hto2B_WtoLNu

############## VVV inclusive ##############
VVV:
  name: "VVV"
  color: kOrange-4
  color_mplhep: plum
  datasets:
    - WWW_4F
    - WWZ_4F
    - WZZ
    - ZZZ

############## ST ##############
ST:
  name: "ST"
  color: kCyan-1
  color_mplhep: lightgreen
  datasets:
    - TbarBtoLminusNuB_s_channel_4FS
    - TBbartoLplusNuBbar_s_channel_4FS
    - TbarBQ_t_channel_4FS
    - TBbarQ_t_channel_4FS


############## TW ##############
TW:
  name: "TW"
  color: kCyan-1
  color_mplhep: olivedrab
  datasets:
    - TWminusto2L2Nu
    - TWminusto4Q
    - TWminustoLNu2Q
    - TbarWplusto2L2Nu
    - TbarWplusto4Q
    - TbarWplustoLNu2Q

############## TTX ##############
TTX:
  name: "TT+X"
  color: kBlue-10
  color_mplhep: red
  datasets:
    - TTWH
    - TTWW
    - TTZH
    - TTZZ
    - TTZ_Zto2Q


############## VBF signal ##############

VBFHto2Mu:
  name: "VBFHto2Mu"
  color: "kPink"
  color_mplhep: magenta
  datasets:
    - VBFHto2Mu

############## ggH signal ##############

GluGluHto2Mu:
  name: "GluGluHto2Mu"
  color: "kCyan"
  color_mplhep: cyan
  datasets:
    - GluGluHto2Mu

############## VH signal ##############

VHto2Mu:
  name: "VHto2Mu"
  color: "kPink"
  color_mplhep: red
  datasets:
    - WminusH_Hto2Mu_WtoAll
    - WplusH_Hto2Mu_WtoAll
    - ZH_Hto2Mu_ZtoAll

############## TTH signal ##############

TTHto2Mu:
  name: "TTHto2Mu"
  color: "kPink"
  color_mplhep: red
  datasets:
    - TTHto2Mu

TTH_inclusive:
  name: "ttH"
  color: "kpink"
  color_mplhep: red
  datasets:
    - TTHtoNon2B_M125
    - TTHto2B_M125

Data_Full:
  name: "Data"
  datasets:
    - EGamma_Run2022E
    - EGamma_Run2022F
    - EGamma_Run2022G
    - Muon_Run2022E
    - Muon_Run2022F
    - Muon_Run2022G
    - MuonEG_Run2022E
    - MuonEG_Run2022F
    - MuonEG_Run2022G

Data_EGamma:
  name: "Data EGamma"
  datasets:
    - EGamma_Run2022E
    - EGamma_Run2022F
    - EGamma_Run2022G

Data_Muon:
  name: "Data Muon"
  datasets:
    - Muon_Run2022E
    - Muon_Run2022F
    - Muon_Run2022G

Data_MuonEG:
  name: "Data MuonEG"
  datasets:
    - MuonEG_Run2022E
    - MuonEG_Run2022F
    - MuonEG_Run2022G
