GLOBAL:
  sampleSelection:
    - drop ^.*
    - keep ^TTto.*
    - keep ^ttH.*
    # - keep ^ST.*
    - keep DYto2L_M_10to50_amcatnloFXFX
    - keep DYto2L_M_50_amcatnloFXFX
    - keep WtoLNu_amcatnloFXFX
    - keep WW
    - keep WZ
    - keep ZZ
    - keep WWW_4F
    - keep WWZ_4F
    - keep WZZ
    - keep ZZZ
    - keep ^Muon_.*
    # - keep ^Tau_.*
    # - keep ^EGamma_.*
    # - keep ^MuonEG_.*
    # - keep ^Jet.*
    # - keep ^MET_.*
  use_stitching: false
  triggerFile: config/Run3_2022EE/triggers.yaml
