meta_data:
  batch_dict: # here go samples for training
    batch_size: 33
    nBatches: 1000
  # iterate_cut: (lep1_type >= 0) & (lep2_type >= 0) & (event%4 == 0)
  global_config: /afs/cern.ch/user/a/ayeagle/H_mumu/config/global.yaml
  general_config: /afs/cern.ch/user/a/ayeagle/H_mumu/Studies/DNN/ds_setup/general.yaml
  temp_folder: /eos/user/a/ayeagle/H_mumu/temp_files/
  output_folder: /eos/user/a/ayeagle/H_mumu/root_files/v2/Run3_2022
  input_folder: /eos/user/v/vdamante/H_mumu/anaTuples/v2/Run3_2022
  output_name: ZZ.root

processes:
# - batch_size: 49
#   batch_start: 0
#   datasets:
#   - WWto2L2Nu_powheg
#   - WWto2L2Nu_powheg_ext1
#   - WWto4Q_powheg
#   - WWto4Q_powheg_ext1
#   - WWtoLNu2Q_powheg
#   - WWtoLNu2Q_powheg_ext1
# - batch_size: 104
#   batch_start: 0
#   datasets:
#   - WZto2L2Q_powheg
#   - WZto2L2Q_powheg_ext1
#   - WZto3LNu_powheg
#   - WZtoLNu2Q_powheg
#   - WZtoLNu2Q_powheg_ext1
# - batch_size: 33
#   batch_start: 0
#   datasets:
#   - ZZto2L2Nu_powheg_ext1
#   - ZZto2L2Q_powheg_ext1
#   - ZZto2Nu2Q_powheg
#   - ZZto2Nu2Q_powheg_ext1
#   - ZZto4L_powheg
#   - ZZto4L_powheg_ext1
# - batch_size: 1375
#   batch_start: 0
#   datasets:
#   - TTto2L2Nu_ext1
#   - TTto4Q
#   - TTto4Q_ext1
#   - TTtoLNu2Q
#   - TTtoLNu2Q_ext1
# - batch_size: 162
#   batch_start: 0
#   datasets:
#   - LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole
#   - LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_ext1
#   - LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_ext2
# - batch_size: 5012 #14790
#   batch_start: 0
#   datasets:
#   - DYto2L_M_50_amcatnloFXFX
#   - DYto2L_M_50_amcatnloFXFX_ext1
#   - DYto2L_M_50_0J_amcatnloFXFX
#   - DYto2L_M_50_1J_amcatnloFXFX
#   - DYto2L_M_50_2J_amcatnloFXFX
# - batch_size: 720
#   batch_start: 0
#   datasets:
#   - GluGluHto2Mu
# - batch_size: 246
#   batch_start: 0
#   datasets:
#   - VBFHto2Mu
