meta_data:
  nBatches: 1000
  global_config: /afs/cern.ch/user/a/ayeagle/H_mumu/config/global.yaml
  general_config: /afs/cern.ch/user/a/ayeagle/H_mumu/Studies/DNN/ds_setup/general.yaml
  temp_folder: /eos/user/a/ayeagle/H_mumu/temp_files/
  output_folder: /eos/user/a/ayeagle/H_mumu/root_files/v2/Run3_2022/test1
  input_folder: /eos/user/v/vdamante/H_mumu/anaTuples/v2/Run3_2022

dataset_list:
#  - WWto2L2Nu_powheg
#  - WWto2L2Nu_powheg_ext1
#  - WWto4Q_powheg
#  - WWto4Q_powheg_ext1
#  - WWtoLNu2Q_powheg
#  - WWtoLNu2Q_powheg_ext1
#  - WZto2L2Q_powheg
#  - WZto2L2Q_powheg_ext1
#  - WZto3LNu_powheg
#  - WZtoLNu2Q_powheg
#  - WZtoLNu2Q_powheg_ext1
#  - ZZto2L2Nu_powheg_ext1
#  - ZZto2L2Q_powheg_ext1
#  - ZZto2Nu2Q_powheg
#  - ZZto2Nu2Q_powheg_ext1
#  - ZZto4L_powheg
#  - ZZto4L_powheg_ext1
#  - TTto2L2Nu
#  - TTto2L2Nu_ext1
#  - TTto4Q
#  - TTto4Q_ext1
#  - TTtoLNu2Q
#  - TTtoLNu2Q_ext1
#  - LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole
#  - LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_ext1
#  - LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_ext2
#  - LLJJ_SM_M-50_MJJ120_13p6TeV_dipole
#  - LLJJ_SM_M-50_MJJ120_13p6TeV_dipole_ext1
#  - DYto2L_M_10to50_amcatnloFXFX
#  - DYto2L_M_50_amcatnloFXFX
#  - DYto2L_M_50_amcatnloFXFX_ext1
#  - DYto2L_M_50_0J_amcatnloFXFX
#  - DYto2L_M_50_1J_amcatnloFXFX
#  - DYto2L_M_50_2J_amcatnloFXFX
#  - DYto2Mu_MLL_105to160_amcatnloFXFX
#  - GluGluHto2Mu
#  - VBFHto2Mu
  - TT
  - ZZto2L2Nu_powheg
  - ZZto2L2Q_powheg