
[meta]
results_dir = "/afs/cern.ch/user/a/ayeagle/H_mumu/Studies/DNN/results"
use_cuda = true

[dataloader]
additional_cut = 'VBF_JetVeto'
valid_size = 0.20
test_size = 0.35
signal_types = [31]
columns_config = '/afs/cern.ch/user/a/ayeagle/H_mumu/Studies/DNN/ds_setup/general.yaml'

[network]
# Hidden layers + output layer only
# Input layer size pulled from the used columns
layer_list = [60, 60, 60, 60, 30, 1]

[training]
batch_size = 600
epochs = 4000
early_stop = false
patience = 10

[optimizer]
lr = 2.5e-06
momentum = 0.9
dampening = 0.2
weight_decay = 0.0
