
[meta]
results_dir = "/afs/cern.ch/user/a/ayeagle/H_mumu/Studies/DNN/results"
use_cuda = true

[dataloader]
additional_cut = '(VBF_JetVeto) & (Signal_Fit)'
#additional_cut = '(VBF_JetVeto)'
# x_size are the fraction of all data post-cut to use for each set
# train_size gets what is left (1 - valid_size - test_size)
valid_size = 0.20
test_size = 0.35
signal_types = [32]
columns_config = '/afs/cern.ch/user/a/ayeagle/H_mumu/Studies/DNN/ds_setup/general.yaml'

[network]
# Hidden layers + output layer only
# Input layer size pulled from the used columns
layer_list = [50, 50, 50, 50, 1]
dropout = 0.1

[training]
batch_size = 1000
epochs = 1000
early_stop = false
patience = 250

[optimizer]
algo = "Adam"   # Currently, SGD and Adam are supported
lr = 1e-05
weight_decay = 0.0
#momentum = 0.9
#dampening = 0.2


