
mu1_pt:
  x_bins: "200|0:1000"
  x_rebin:
    other: [20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180,190, 200, 250]
  x_title: p_{T}(lep_{1}) (GeV)
  y_title: "#frac{Events}{bin width} #left(#frac{1}{GeV}#right) "
  #y_title: Events
  use_log_y: False
  max_y_sf: 1.8
  # use_log_y: True
  # max_y_sf: 20.2
  divide_by_bin_width: True
  #divide_by_bin_width: False


mu1_eta:
  x_bins: "100|-2.5:2.5"
  x_rebin: [-2.5, -2.3, -2.1, -1.9, -1.7, -1.5, -1.3, -1.1, -0.9, -0.7, -0.5, -0.3, -0.1, 0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.1, 2.3, 2.5]
  x_title: \eta(lep_{1})
  y_title: Events
  use_log_y: False
  max_y_sf: 1.8
  divide_by_bin_width: False

mu1_phi:
  x_bins: "100|-3.2:3.2"
  x_rebin: [-3.2, -2.88, -2.56, -2.24, -1.92, -1.6, -1.28, -0.96, -0.64, -0.32, -0.0, 0.32, 0.64, 0.96, 1.28, 1.6, 1.92, 2.24, 2.56, 2.88, 3.2]
  x_title: \phi(lep_{1})
  y_title: Events
  use_log_y: False
  max_y_sf: 1.8
  divide_by_bin_width: False


########## tau1 END ##########


pt_ll:
  x_bins: "200|0:1000"
  x_rebin:
    other: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 105, 120, 135, 150, 165, 180, 200, 300]
  x_title: p_{T}(lep_{1}, lep_{2}) (GeV)
  y_title: "#frac{Events}{bin width} #left(#frac{1}{GeV}#right) "
  y_title: Events
  use_log_x: False
  use_log_y: False
  max_y_sf: 1.8
  # use_log_y: True
  # max_y_sf: 20.2
  divide_by_bin_width: True

m_mumu:
  x_bins: "200|0:1000"
  x_rebin:
    other: [0,10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110,120, 130,140, 150,160, 170,180, 190,200, 220,240, 260,280,300, 350]
  x_title: M^{\tau\tau}_{vis} (GeV)
  # y_title: Events
  y_title: "#frac{Events}{bin width} #left(#frac{1}{GeV}#right) "
  use_log_x: False
  use_log_y: False
  max_y_sf: 1.8
  # use_log_y: True
  # max_y_sf: 20.2
  # divide_by_bin_width: False
  divide_by_bin_width: True

dR_mumu:
  x_bins: "50|0:5"
  x_rebin: [0.5, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2, 2.4, 2.6, 2.8, 3.0]
  x_title: \Delta R(\tau\tau)
  y_title: Events
  use_log_y: False
  max_y_sf: 1.8
  divide_by_bin_width: False
