# - name: QCD
#   types:
#     - QCD
#   title: QCD
#   color: kBlue-10
- name: DY
  types:
    - DY
  title: "DY #rightarrow ll + jets"
  color: kAzure-9
- name: VV
  types:
    - VV
  title: "VV"
  color: kPink+2 # kOrange-4
- name: W
  types:
   - W
  title: "W #rightarrow l#nu + jets"
  color: kYellow-7
- name: TT
  types:
    - TT
  title: t#bar{t}
  color: kSpring+5
- name: VVV
  types:
    - VVV
  title: "VVV"
  color: kOrange-4
# - name: ST
#   types:
#     - ST
#   title: "ST"
#   color: kYellow-9
# - name: single_H
#   title: "H"
#   types:
#     - ttH
#     - VH
#     - H
  # color: kRed-10
# - name: Other
#   title: "Other"
#   types: []
#   color: kPink+2
- name: data
  title: "data obs"
  types:
    - data
  type: data