- name: DY
  types:
    - DY
  title: "DY $\\rightarrow \\ell \\ell$ + jets"
  color: kAzure-9
  color_mplhep: lightskyblue

- name: VV
  types:
    - VV
    # - VVV
  title: "VV"
  color: kPink+2
  color_mplhep: tomato

- name: TT
  types:
    - TT
  # title: t#bar{t} #
  title: "t $\\bar{t}$"
  color: kSpring+5
  color_mplhep: darkblue #turquoise

- name: W
  types:
    - W
  # title: "W #rightarrow l#nu + jets" #
  title: "W $\\rightarrow \\ell \\nu$+ jets"
  color: kYellow-7
  color_mplhep: yellow

- name: EWK
  types:
    - EWK
  title: "EWK"
  color: kMagenta+3
  color_mplhep: darkmagenta



- name: VVV
  types:
    - VVV
  title: "VVV"
  color: kOrange-4
  color_mplhep: plum

- name: TTX
  types:
    - TTX
  title: "TT+X"
  color: kBlue-10
  color_mplhep: pink

- name: ST
  types:
    - ST
    # - TW
  title: "channelSelection"
  color: kCyan-1
  color_mplhep: green

- name: TW
  title: "TW"
  types:
    - TW
  color: kRed-10
  color_mplhep: red


- name: GluGluHto2Mu
  type: signal
  types:
    - ggH
    # - VBFH
  title: "ggH"
  color: "kCyan"
  color_mplhep: cyan
  # scale: 100.

- name: VBFHto2Mu
  type: signal
  types:
    - VBFH
  title: "VBFH"
  color: "kPink"
  color_mplhep: red
  # scale: 100

- name: data
  title: "data obs"
  types:
    - data
  type: data


# - name: Other
#   title: "Other"
#   types: []
#   color: kPink+2

# - name: Other
#   title: "Other"
#   types: []
#   color: kCyan-1
#   color_mplhep: green
