############## WJetsToLNu ##############
WtoLNu_amcatnloFXFX:
  sampleType: W
# WtoLNu_0J_amcatnloFXFX:
  # sampleType: W
# WtoLNu_1J_amcatnloFXFX:
  # sampleType: W
# WtoLNu_2J_amcatnloFXFX:
  # sampleType: W

############## TT ##############
# TT:
#   sampleType: TT
# TTto2L2Nu:
#   sampleType: TT
# TTto4Q:
#   sampleType: TT
# TTtoLNu2Q:
#   sampleType: TT

# TT_ext1:
#   sampleType: TT
# TTto2L2Nu_ext1:
#   sampleType: TT
# TTto4Q_ext1:
#   sampleType: TT
# TTtoLNu2Q_ext1:
#   sampleType: TT

# TTH_Hto2Mu
############## DY ##############


# DYto2L_M_10to50_amcatnloFXFX:
#   sampleType: DY
# DYto2L_M_50_0J_amcatnloFXFX:
#   sampleType: DY
# DYto2L_M_50_1J_amcatnloFXFX:
#   sampleType: DY
# DYto2L_M_50_2J_amcatnloFXFX:
  # sampleType: DY
DYto2L_M_50_amcatnloFXFX:
  sampleType: DY
# DYto2L_M_50_amcatnloFXFX_ext1:
#   sampleType: DY
# DYto2Mu_MLL_105to160_amcatnloFXFX:
#   sampleType: DY
# DYto2Mu_MLL_120to200_powheg:
#   sampleType: DY
# DYto2Mu_MLL_200to400_powheg:
#   sampleType: DY
# DYto2Mu_MLL_50to120_powheg:
#   sampleType: DY



############## EWK ##############
# EWK_ZTo2L:
#   sampleType: EWK
# EWK_ZTo2Nu:
#   sampleType: EWK
# EWK_WplusToLNu:
#   sampleType: EWK
# EWK_WminusToLNu:
#   sampleType: EWK


LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole:
  sampleType: EWK
# LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_ext1:
#   sampleType: EWK
# LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_ext2:
#   sampleType: EWK
# LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter:
#   sampleType: EWK
# LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter_ext1:
#   sampleType: EWK
# LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter_ext2:
#   sampleType: EWK
# LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter_ext3:
#   sampleType: EWK
# LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter_ext4:
#   sampleType: EWK
# LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter_ext5:
#   sampleType: EWK
# LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter_ext6:
#   sampleType: EWK
# LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter_ext7:
#   sampleType: EWK
# LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter_ext8:
#   sampleType: EWK
# LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter_ext9:
#   sampleType: EWK
# LLJJ_SM_M-50_MJJ120_13p6TeV_dipole:
#   sampleType: EWK
# LLJJ_SM_M-50_MJJ120_13p6TeV_dipole_ext1:
#   sampleType: EWK


############## single Higgs ##############
# ggHToZZTo2L2Q:
#   sampleType: H
# GluGluHToTauTau_M125:
#   sampleType: H
# VBFHToTauTau_M125:
#   sampleType: H
# GluGluHToWWTo2L2Nu_M125:
#   sampleType: H
# VBFHToWWTo2L2Nu_M125:
#   sampleType: H

############## VH non-inclusive ##############
# WplusHToTauTau_M125:
#   sampleType: VH
# WminusHToTauTau_M125:
#   sampleType: VH
# ZHToTauTau_M125:
#   sampleType: VH
# ZH_Hbb_Zll:
#   sampleType: VH
# ZH_Hbb_Zqq:
#   sampleType: VH
# HWplusJ_HToWW_M125:
#   sampleType: VH
# HWminusJ_HToWW_M125:
#   sampleType: VH
# HZJ_HToWW_M125:
#   sampleType: VH

############## VV inclusive ##############
# WW:
#   sampleType: VV
# WZ:
#   sampleType: VV
# ZZ:
#   sampleType: VV
############## VV non inclusive ##############
# WW:
#   sampleType: VV
WWto2L2Nu_powheg:
  sampleType: VV
# WWto2L2Nu_powheg_ext1:
#   sampleType: VV
WWto4Q_powheg:
  sampleType: VV
# WWto4Q_powheg_ext1:
#   sampleType: VV
WWtoLNu2Q_powheg:
  sampleType: VV
# WWtoLNu2Q_powheg_ext1:
#   sampleType: VV

# WZ:
#   sampleType: VV
WZto3LNu_powheg:
  sampleType: VV
WZto2L2Q_powheg:
  sampleType: VV
# WZto2L2Q_powheg_ext1:
#   sampleType: VV
WZtoLNu2Q_powheg:
  sampleType: VV
# WZtoLNu2Q_powheg_ext1:
#   sampleType: VV

# ZZ:
#   sampleType: VV
# ZZto2L2Nu_powheg:
#   sampleType: VV
# ZZto2L2Nu_powheg_ext1:
#   sampleType: VV
# ZZto2L2Q_powheg:
#   sampleType: VV
# ZZto2L2Q_powheg_ext1:
#   sampleType: VV
ZZto2Nu2Q_powheg:
  sampleType: VV
# ZZto2Nu2Q_powheg_ext1:
  # sampleType: VV
ZZto4L_powheg:
  sampleType: VV
# ZZto4L_powheg_ext1:
  # sampleType: VV

# ############## VVV inclusive ##############
WWW_4F:
  sampleType: VVV
WWZ_4F:
  sampleType: VVV
WZZ:
  sampleType: VVV
ZZZ:
  sampleType: VVV

# ############## ST #############
# ST_t_channel_antitop_4f_InclusiveDecays:
#   sampleType: ST
# ST_t_channel_top_4f_InclusiveDecays:
#   sampleType: ST
ST_tW_antitop_2L2Nu:
  sampleType: ST
# ST_tW_antitop_4Q:
#   sampleType: ST
# ST_tW_antitop_LNu2Q:
#   sampleType: ST
ST_tW_top_2L2Nu:
  sampleType: ST
# ST_tW_top_4Q:
#   sampleType: ST
# ST_tW_top_LNu2Q:
#   sampleType: ST


TbarWplusto4Q:
  sampleType: ST
TbarWplustoLNu2Q:
  sampleType: ST

TbarBQ_t_channel_4FS:
  sampleType: ST
TbarBtoLminusNuB_s_channel_4FS:
  sampleType: ST
TbarWplusto2L2Nu:
  sampleType: ST

TBbarQ_t_channel_4FS:
  sampleType: ST
TbarWplusto2L2Nu:
  sampleType: ST
TBbartoLplusNuBbar_s_channel_4FS:
  sampleType: ST
TbarWplusto2L2Nu:
  sampleType: ST

# ############## TW ##############

TWminusto2L2Nu:
  sampleType: TW
# TWminusto2L2Nu_ext1:
  # sampleType: TW
TWminusto4Q:
  sampleType: TW
# TWminusto4Q_ext1:
  # sampleType: TW
TWminustoLNu2Q:
  sampleType: TW
# TWminustoLNu2Q_ext1:
  # sampleType: TW

# ############## TTX inclusive ##############
TTWW:
  sampleType: TTX
TTWH:
  sampleType: TTX
TTZH:
  sampleType: TTX
TTZZ:
  sampleType: TTX

# ############## TTX non-inclusive ##############
TTZ_Zto2Q:
  sampleType: TTX

# ############## ttH ##############
# ttHToNonbb_M125:
#  sampleType: ttH
# ttHTobb_M125:
#   sampleType: ttH