############## WJetsToLNu ##############
WtoLNu_amcatnloFXFX:
  sampleType: W
# WtoLNu_0J_amcatnloFXFX:
#   sampleType: W
# WtoLNu_1J_amcatnloFXFX:
#   sampleType: W
# WtoLNu_2J_amcatnloFXFX:
#   sampleType: W

############## TT ##############
TTto2L2Nu:
  sampleType: TT
TTto4Q:
  sampleType: TT
TTtoLNu2Q:
  sampleType: TT

# TT_ext1:
#   sampleType: TT
# TTto2L2Nu_ext1:
#   sampleType: TT
# TTto4Q_ext1:
#   sampleType: TT
# TTtoLNu2Q_ext1:
#   sampleType: TT

# TTH_Hto2Mu
############## DY ##############


# DYto2L_M_10to50_amcatnloFXFX:
#   sampleType: DY
# DYto2L_M_50_amcatnloFXFX:
#   sampleType: DY
# DYto2Mu_MLL_105to160_amcatnloFXFX:
#   sampleType: DY
# DYto2Mu_MLL_120to200_powheg:
#   sampleType: DY
# DYto2Mu_MLL_200to400_powheg:
#   sampleType: DY
# DYto2Mu_MLL_50to120_powheg:
#   sampleType: DY
# DYToMuMu-M50_13p6TeV_MiNNLO_pythia8:
#   sampleType: DY
DYto2L_M_50_amcatnloFXFX:
  sampleType: DY


############## EWK ##############
# EWK_ZTo2L:
#   sampleType: EWK
# EWK_ZTo2Nu:
#   sampleType: EWK
# EWK_WplusToLNu:
#   sampleType: EWK
# EWK_WminusToLNu:
#   sampleType: EWK

# LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole:
#   sampleType: EWK
# LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_ext1:
#   sampleType: EWK
# LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_ext2:
#   sampleType: EWK
# LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter:
#   sampleType: EWK
# LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter_ext1:
#   sampleType: EWK
# LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter_ext2:
#   sampleType: EWK
# LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter_ext3:
#   sampleType: EWK
# LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter_ext4:
#   sampleType: EWK
# LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter_ext5:
#   sampleType: EWK
# LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter_ext6:
#   sampleType: EWK
# LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter_ext7:
#   sampleType: EWK
# LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter_ext8:
#   sampleType: EWK
# LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter_ext9:
#   sampleType: EWK
LLJJ_SM_M-50_MJJ120_13p6TeV_dipole:
  sampleType: EWK
# LLJJ_SM_M-50_MJJ120_13p6TeV_dipole_ext1:
#   sampleType: EWK


############## single Higgs ##############
# ggHToZZTo2L2Q: # --> missing
#   sampleType: H
# GluGluHto2Wto2L2Nu_M125:
#   sampleType: H
# VBFHto2Wto2L2Nu_M125:
#   sampleType: H
# GluGluHto2B_M125:
#   sampleType: H
# VBFHto2B_M125:
#   sampleType: H

############## VH non-inclusive ##############
# WplusHToTauTau_M125:
#   sampleType: VH
# WminusHToTauTau_M125:
#   sampleType: VH
# ZHToTauTau_M125:
#   sampleType: VH
ZH_Hto2B_Zto2L:
  sampleType: VH
ZH_Hto2B_Zto2Q:
  sampleType: VH
# ZH_Hto2Mu_ZtoAll:
#   sampleType: VH
ggZH_Hto2B_Zto2L:
  sampleType: VH
ggZH_Hto2B_Zto2Q:
  sampleType: VH
WminusH_Hto2B_Wto2Q:
  sampleType: VH
WminusH_Hto2B_WtoLNu:
  sampleType: VH
# WminusH_Hto2Mu_WtoAll:
#  sampleType: VH
WplusH_Hto2B_Wto2Q:
  sampleType: VH
WplusH_Hto2B_WtoLNu:
  sampleType: VH

############## VV inclusive ##############
# WW:
#   sampleType: VV
# WZ:
#   sampleType: VV
# ZZ:
#   sampleType: VV
############## VV non inclusive ##############
WWto2L2Nu_powheg:
  sampleType: VV
# WWto2L2Nu_powheg_ext1:
#   sampleType: VV
WWto4Q_powheg:
  sampleType: VV
# WWto4Q_powheg_ext1:
#   sampleType: VV
WWtoLNu2Q_powheg:
  sampleType: VV
# WWtoLNu2Q_powheg_ext1:
#   sampleType: VV

WZto3LNu_powheg:
  sampleType: VV
WZto2L2Q_powheg:
  sampleType: VV
# WZto2L2Q_powheg_ext1:
#   sampleType: VV
WZtoLNu2Q_powheg:
  sampleType: VV
# WZtoLNu2Q_powheg_ext1:
#   sampleType: VV


ZZto2L2Nu_powheg:
  sampleType: VV
# ZZto2L2Nu_powheg_ext1:
#   sampleType: VV
ZZto2L2Q_powheg:
  sampleType: VV
# ZZto2L2Q_powheg_ext1:
#   sampleType: VV
ZZto2Nu2Q_powheg:
  sampleType: VV
# ZZto2Nu2Q_powheg_ext1:
#   sampleType: VV
ZZto4L_powheg:
  sampleType: VV
# ZZto4L_powheg_ext1:
#   sampleType: VV

# ############## VVV inclusive ##############
WWW_4F:
  sampleType: VVV
WWZ_4F:
  sampleType: VVV
WZZ:
  sampleType: VVV
ZZZ:
  sampleType: VVV

# ############## ST #############
### previous notation ####
# ST_t_channel_antitop_4f_InclusiveDecays:
#   sampleType: ST
# ST_t_channel_top_4f_InclusiveDecays:
#   sampleType: ST
# ST_tW_antitop_2L2Nu:
#   sampleType: ST
# ST_tW_antitop_4Q:
#   sampleType: ST
# ST_tW_antitop_LNu2Q:
#   sampleType: ST
# ST_tW_top_2L2Nu:
#   sampleType: ST
# ST_tW_top_4Q:
#   sampleType: ST
# ST_tW_top_LNu2Q:
#   sampleType: ST

### new notation ###
TbarBtoLminusNuB_s_channel_4FS:
  sampleType: ST
TBbartoLplusNuBbar_s_channel_4FS:
  sampleType: ST
TbarBQ_t_channel_4FS:
  sampleType: ST
TBbarQ_t_channel_4FS:
  sampleType: ST

# ############## TW ##############
TWminusto2L2Nu:
  sampleType: TW
# TWminusto2L2Nu_ext1:
#   sampleType: TW
TWminusto4Q:
  sampleType: TW
# TWminusto4Q_ext1:
#   sampleType: TW
TWminustoLNu2Q:
  sampleType: TW
# TWminustoLNu2Q_ext1:
#   sampleType: TW
TbarWplusto2L2Nu:
  sampleType: TW
# TbarWplusto2L2Nu_ext1:
#   sampleType: TW
TbarWplusto4Q:
  sampleType: TW
# TbarWplusto4Q_ext1:
#   sampleType: TW
TbarWplustoLNu2Q:
  sampleType: TW
# TbarWplustoLNu2Q_ext1:
#   sampleType: TW

# ############## TTX inclusive ##############
TTWW:
  sampleType: TTX
TTWH:
  sampleType: TTX
TTZH:
  sampleType: TTX
TTZZ:
  sampleType: TTX

# ############## TTX non-inclusive ##############
TTZ_Zto2Q:
  sampleType: TTX

# ############## ttH ##############
# TTHtoNon2B_M125:
#  sampleType: ttH
# TTHto2B_M125:
#   sampleType: ttH
