anaTupleDef: AnaProd/anaTupleDef.py
analysis_import: Analysis.H_mumu
signal_types:
  - ggH
  - VBFH
  # - ttH
  # - VH
storeFatJets: False

bjet_preselection_branch : "Jet_B1"
tagger_name: particleNet
met_type: "PuppiMET"

channelSelection:
  - muMu

channelDefinition:
  eTau: 13
  muTau: 23
  tauTau: 33
  eE: 11
  eMu: 12
  muMu: 22


corrections:
  # - JEC
  # - JER
  - trg
  # - btagWP
  - mu
  - Vpt
  - pu

region: All
region_default: All

SignRegions:
  - OS
ApplyBweight: False
triggers:
  muMu: [singleMu]
hist_triggers:
  muMu:
    default:  (HLT_singleMu)

categories:
  - baseline
  - ggH
  - VBF
  - baseline_Zmumu
  - ggH_Zmumu
  - VBF_Zmumu



category_definition:
  baseline: "(mu1_pt > {MuPtTh} && mu2_pt > {MuPtTh}) "
  VBF: "baseline && HasVBF && VBFjet1_pt > 25 && VBFjet2_pt >25"
  ggH: "baseline && !(VBF)"
  baseline_Zmumu: "(mu1_pt > {MuPtTh} && mu2_pt > {MuPtTh}) && DYEnriched"
  VBF_Zmumu: "baseline_Zmumu && VBF "
  ggH_Zmumu: "baseline_Zmumu && !(VBF) "

  VBF_JetVeto: "(VBF && (VBFjet1_pt > 50 && abs(VBFjet1_eta) >= 2.5 && abs(VBFjet1_eta) =< 3 ) || (VBFjet2_pt > 50 && abs(VBFjet2_eta) >= 2.5 && abs(VBFjet2_eta) =< 3 ))"
  ggH_VBFJetVeto: "baseline && !(VBF_JetVeto)"

  VBF_Zmumu_JetVeto: "baseline_Zmumu && VBF_JetVeto"
  ggH_Zmumu_JetVeto: "baseline_Zmumu && !VBF_JetVeto"


singleMu_th:
  "Run2_2016": 26
  "Run2_2016_HIPM": 26
  "Run2_2017": 29
  "Run2_2018": 26
  "Run3_2022": 26
  "Run3_2022EE": 26


scales:
  - Up
  - Down


sample_types_to_merge:
  - DY
  - TT
  - W
  - VVV
  - VV
  - ttH
  # - ST
  # - TTVV