anaTupleDef: AnaProd/anaTupleDef.py
analysis_import: Analysis.H_mumu
signal_types:
 - DY
storeFatJets: False

bjet_preselection_branch : "Jet_B1"
tagger_name: particleNet
met_type: "PuppiMET"

channelSelection:
  - muMu

channelDefinition:
  eTau: 13
  muTau: 23
  tauTau: 33
  eE: 11
  eMu: 12
  muMu: 22


corrections:
  # - JEC
  # - JER
  - trg
  # - btagWP
  - mu
  - pu

region: Inclusive
region_default: Inclusive

SignRegions:
  - OS
ApplyBweight: False
triggers:
  muMu: [singleMu]
hist_triggers:
  muMu:
    default:  (HLT_singleMu)

categories:
  - ggH
  - VBF



category_definition:
  VBF: "(mu1_pt > {MuPtTh} && mu2_pt > {MuPtTh}) && HasVBF && {region}"
  ggH: "(mu1_pt > {MuPtTh} && mu2_pt > {MuPtTh}) && !(VBF) && {region}"


singleMu_th:
  "Run2_2016": 26
  "Run2_2016_HIPM": 26
  "Run2_2017": 29
  "Run2_2018": 26
  "Run3_2022": 26
  "Run3_2022EE": 26


scales:
  - Up
  - Down


sample_types_to_merge:
  - DY
  - TT
  - W
  - VVV
  - VV
  - ttH
  # - ST
  # - TTVV