GluGluHto2Mu:
  sampleType: ggH

TTH_Hto2Mu:
  sampleType: ttH

VBFHto2Mu:
  sampleType: VBFH
VBFHto2Mu_M-125_13p6TeV_powheg-herwig7:
  sampleType: VBFH
# VBFHto2Mu_M-125_13p6TeV_powheg-herwig7_ext1:
#   sampleType: VBFH
# VBFHto2Mu_M-125_13p6TeV_powheg-herwig7_ext2:
#   sampleType: VBFH

WminusH_Hto2Mu_WtoAll:
  sampleType: VH
WplusH_Hto2Mu_WtoAll:
  sampleType: VH
ZH_Hto2Mu_ZtoAll:
  sampleType: VH
