WWto2L2Nu_powheg = [2]
WWto2L2Nu_powheg_ext1 = [2]
WWtoLNu2Q_powheg = [2]
WWtoLNu2Q_powheg_ext1 = [2]

WZto2L2Q_powheg = [2]
WZto2L2Q_powheg_ext1 = [2]
WZto3LNu_powheg = [1]

ZZto2L2Nu_powheg = [2]
ZZto2L2Nu_powheg_ext1 = [2]
ZZto2L2Q_powheg = [2]
ZZto2L2Q_powheg_ext1 = [2]
ZZto4L_powheg = [2]
ZZto4L_powheg_ext1 = [2]

TTto2L2Nu = [2]
TTto2L2Nu_ext1 = [2]
TTtoLNu2Q = [2]
TTtoLNu2Q_ext1 = [2]

LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole = [4]
LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_ext1 = [4]
LLJJ_SM_M-50_MJJ120_13p6TeV_dipole = [4]
LLJJ_SM_M-50_MJJ120_13p6TeV_dipole_ext1 = [4]

DYto2L_M_50_amcatnloFXFX = [4]
DYto2L_M_50_amcatnloFXFX_ext1 = [4]
DYto2L_M_50_0J_amcatnloFXFX = [4]
DYto2L_M_50_1J_amcatnloFXFX = [4]
DYto2L_M_50_2J_amcatnloFXFX = [4]
DYto2Mu_MLL_105to160_amcatnloFXFX = [4]

GluGluHto2Mu = [1]
VBFHto2Mu = [1]