# https://twiki.cern.ch/twiki/bin/viewauth/CMS/TauTrigger#Updates_for_2022_data_taking
# https://twiki.cern.ch/twiki/bin/viewauth/CMS/TauTrigger#Updates_for_2022_data_taking

singleMu:
  channels:
    - muMu
  path:
    - HLT_IsoMu24  # ####  COMPARISON WITH RUN2 #### --> What whas done in Run2 analysis: Require event to pass HLT IsoMu24 or HL IsoTkMu24 triggers in 2016, HLT IsoMu27 in 2017 and HLT IsoMu24 in 2018. -- See AN/2019_185 lines 123 - 130
  legs:
    - offline_obj:
        cut: "{obj}_legType == Leg::mu && {obj}_pt > 26"  # selection for offline object matching to the trigger, same w.r.t. run 2
      online_obj:
        cut: TrigObj_id == 13 && (TrigObj_filterBits&8)!=0  # selection for online object matching to the trigger, same w.r.t. run2
      doMatching: True
      jsonTRGcorrection_key:
        2022_Summer22: NUM_IsoMu24_DEN_CutBasedIdMedium_and_PFIsoMedium
        2022_Summer22EE: NUM_IsoMu24_DEN_CutBasedIdMedium_and_PFIsoMedium
        2023_Summer23: NUM_IsoMu24_DEN_CutBasedIdMedium_and_PFIsoMedium
        2023_Summer23BPix: NUM_IsoMu24_DEN_CutBasedIdMedium_and_PFIsoMedium
      jsonTRGcorrection_elepath: "placeholder"

