norm:
  PileUp_Lumi_MC:
    expression: weight_MC_Lumi_pu{scale}_rel  * final_weight
    name: CMS_pileup_{}

  HighPt_MuonID_SF_MediumID:
    expression: weight_mu1_HighPt_MuonID_SF_MediumID{scale}_rel * weight_mu2_HighPt_MuonID_SF_MediumID{scale}_rel * final_weight
    name:  CMS_eff_m_id_highpt_{}
  HighPt_MuonID_SF_MediumIDLooseRelIsoHLT:
    expression: weight_mu1_HighPt_MuonID_SF_MediumIDLooseRelIsoHLT{scale}_rel * weight_mu2_HighPt_MuonID_SF_MediumIDLooseRelIsoHLT{scale}_rel * final_weight
    name:  CMS_eff_m_id_iso_hlt_highpt_{}
  HighPt_MuonID_SF_MediumIdLooseRelTkIso:
    expression: weight_mu1_HighPt_MuonID_SF_MediumIdLooseRelTkIso{scale}_rel * weight_mu2_HighPt_MuonID_SF_MediumIdLooseRelTkIso{scale}_rel * final_weight
    name: CMS_eff_m_id_iso_highpt_{}
  HighPt_MuonID_SF_Reco:
    expression: weight_mu1_HighPt_MuonID_SF_Reco{scale}_rel * weight_mu2_HighPt_MuonID_SF_Reco{scale}_rel * final_weight
    name:  CMS_eff_m_reco_highpt_{}
  LowPt_MuonID_SF_MediumID:
    expression: weight_mu1_LowPt_MuonID_SF_MediumID{scale}_rel * weight_mu2_LowPt_MuonID_SF_MediumID{scale}_rel * final_weight
    name:  CMS_eff_m_id_lowpt_{}
  MuonID_SF_LoosePFIso:
    expression: weight_mu1_MuonID_SF_LoosePFIso{scale}_rel * weight_mu2_MuonID_SF_LoosePFIso{scale}_rel * final_weight
    name: CMS_eff_m_iso_{}
  MuonID_SF_MediumIDLoosePFIso:
    expression: weight_mu1_MuonID_SF_MediumIDLoosePFIso{scale}_rel * weight_mu2_MuonID_SF_MediumIDLoosePFIso{scale}_rel * final_weight
    name: CMS_eff_m_id_iso_{}
  MuonID_SF_MediumID_Trk:
    expression: weight_mu1_MuonID_SF_MediumID_Trk{scale}_rel * weight_mu2_MuonID_SF_MediumID_Trk{scale}_rel * final_weight
    name: CMS_eff_m_id_iso_trk_{}

  # HLT_singleMu:
    # expression: weight_trigSF_singleMu_IsoMu24{scale}_rel * final_weight
    # name: CMS_trig_singleMu_{}
  EWKCorr_Vpt:
    expression: weight_EWKCorr_Vpt{scale}_rel * final_weight
    name: CMS_Vpt_{}
  EWKCorr_ewcorr:
    expression: weight_EWKCorr_ewcorr{scale}_rel * final_weight
  name: CMS_ewkCorr_{}
  # DYw_DYWeight:
  #   expression: weight_DYw_DYWeight{scale}_rel * final_weight
  # name: CMS_dyweight_{}

shape:
  - JES_Total
  - JER
  - ScaRe