meta_data:
  batch_dict: # here go samples for training
    GluGluHto2Mu: 100
    TT: 400
    batch_size: 500
  selection_branches: # here go the branches for selection, currently I comment it
  # - lep1_type
  # - lep2_type
  - weight_MC_Lumi_pu
  - event
  # for the moment, keep only event parity
  selection_cut: (tree['event']%4 == 0 )
  iterate_cut: (event%4 == 0 )
  # examples of other cut and iterative cuts --> difference? we will figure out
  # selection_cut: (tree['lep1_type'] >= 0) & (tree['lep2_type'] >= 0) & (tree['event']%4 == 0)
  # iterate_cut: (lep1_type >= 0) & (lep2_type >= 0) & (event%4 == 0)
  storage_folder: /eos/user/v/vdamante/H_mumu/anaTuples/Run3_2022EE_Hmumu_v2/Run3_2022EE/dev
  # empty_dict_example: /afs/cern.ch/work/d/daebi/diHiggs/HH_bbWW/Studies/DNN/DNN_dataset_2024-09-13-13-56-15/GluGlutoRadiontoHHto2B2Vto2B2L2Nu_Combined/GluGlutoRadiontoHHto2B2Vto2B2L2Nu_Combined.root
vars_to_save:
  Muon:
    - mu{}_HasMatching_singleMu
    - mu{}_IP_cov00
    - mu{}_IP_cov10
    - mu{}_IP_cov11
    - mu{}_IP_cov20
    - mu{}_IP_cov21
    - mu{}_IP_cov22
    - mu{}_IPx
    - mu{}_IPy
    - mu{}_IPz
    - mu{}_bField_z
    - mu{}_bsConstrainedChi2
    - mu{}_bsConstrainedPt
    - mu{}_bsConstrainedPtErr
    - mu{}_charge
    - mu{}_dxy
    - mu{}_dxyErr
    - mu{}_dxybs
    - mu{}_dz
    - mu{}_dzErr
    - mu{}_eta
    - mu{}_fsrPhotonIdx
    - mu{}_genPartFlav
    - mu{}_genPartIdx
    - mu{}_gen_charge
    - mu{}_gen_kind
    - mu{}_highPtId
    - mu{}_highPurity
    - mu{}_inTimeMuon
    - mu{}_ip3d
    - mu{}_ipLengthSig
    - mu{}_isGlobal
    - mu{}_isPFcand
    - mu{}_isStandalone
    - mu{}_isTracker
    - mu{}_iso
    - mu{}_jetIdx
    - mu{}_jetNDauCharged
    - mu{}_jetPtRelv2
    - mu{}_jetRelIso
    - mu{}_legType
    - mu{}_looseId
    - mu{}_mass
    - mu{}_mediumId
    - mu{}_mediumPromptId
    - mu{}_miniIsoId
    - mu{}_miniPFRelIso_all
    - mu{}_miniPFRelIso_chg
    - mu{}_multiIsoId
    - mu{}_mvaLowPt
    - mu{}_mvaMuID
    - mu{}_mvaMuID_WP
    - mu{}_nStations
    - mu{}_nTrackerLayers
    - mu{}_pdgId
    - mu{}_pfIsoId
    - mu{}_pfRelIso03_all
    - mu{}_pfRelIso03_chg
    - mu{}_pfRelIso04_all
    - mu{}_phi
    - mu{}_promptMVA
    - mu{}_pt
    - mu{}_ptErr
    - mu{}_pt_rel
    - mu{}_puppiIsoId
    - mu{}_segmentComp
    - mu{}_sip3d
    - mu{}_softId
    - mu{}_softMva
    - mu{}_softMvaId
    - mu{}_softMvaRun3
    - mu{}_svIdx
    - mu{}_tightCharge
    - mu{}_tightId
    - mu{}_tkIsoId
    - mu{}_tkRelIso
    - mu{}_track_cov00
    - mu{}_track_cov10
    - mu{}_track_cov11
    - mu{}_track_cov20
    - mu{}_track_cov21
    - mu{}_track_cov22
    - mu{}_track_cov30
    - mu{}_track_cov31
    - mu{}_track_cov32
    - mu{}_track_cov33
    - mu{}_track_cov40
    - mu{}_track_cov41
    - mu{}_track_cov42
    - mu{}_track_cov43
    - mu{}_track_cov44
    - mu{}_track_dsz
    - mu{}_track_dxy
    - mu{}_track_lambda
    - mu{}_track_phi
    - mu{}_track_qoverp
    - mu{}_triggerIdLoose
    - mu{}_tunepRelPt
    - mu{}_HighPt_MuonID_SF_HighPtIDCentral
    - mu{}_HighPt_MuonID_SF_HighPtIdRelTkIsoCentral
    - mu{}_HighPt_MuonID_SF_RecoCentral
    - mu{}_HighPt_MuonID_SF_TightIDCentral
    - mu{}_LowPt_MuonID_SF_TightIDCentral
    - mu{}_MuonID_SF_LoosePFIsoCentral
    - mu{}_MuonID_SF_MediumIDLooseIsoCentral
    - mu{}_MuonID_SF_MediumID_TrkCentral
    - mu{}_MuonID_SF_TightID_TrkCentral
    - mu{}_TrgSF_singleMu_Central
    - weight_mu{}_HighPt_MuonID_SF_HighPtIDCentral
    - weight_mu{}_HighPt_MuonID_SF_HighPtIdRelTkIsoCentral
    - weight_mu{}_HighPt_MuonID_SF_RecoCentral
    - weight_mu{}_HighPt_MuonID_SF_TightIDCentral
    - weight_mu{}_LowPt_MuonID_SF_TightIDCentral
    - weight_mu{}_MuonID_SF_LoosePFIsoCentral
    - weight_mu{}_MuonID_SF_MediumIDLooseIsoCentral
    - weight_mu{}_MuonID_SF_MediumID_TrkCentral
    - weight_mu{}_MuonID_SF_TightID_TrkCentral
    - weight_mu{}_TrgSF_singleMu_Central
  SelectedJet:
    - PNetRegPtRawCorr
    - PNetRegPtRawCorrNeutrino
    - PNetRegPtRawRes
    - area
    - btagDeepFlavB
    - btagDeepFlavCvB
    - btagDeepFlavCvL
    - btagDeepFlavQG
    - btagPNetB
    - btagPNetCvB
    - btagPNetCvL
    - btagPNetCvNotB
    - btagPNetQvG
    - btagPNetTauVJet
    - chEmEF
    - chHEF
    - chMultiplicity
    - electronIdx1
    - electronIdx2
    - eta
    - genJetIdx
    - hadronFlavour
    - hfEmEF
    - hfHEF
    - hfadjacentEtaStripsSize
    - hfcentralEtaStripSize
    - hfsigmaEtaEta
    - hfsigmaPhiPhi
    - idx
    - jetId
    - mass
    - muEF
    - muonIdx1
    - muonIdx2
    - muonSubtrFactor
    - nConstituents
    - nElectrons
    - nMuons
    - nSVs
    - neEmEF
    - neHEF
    - neMultiplicity
    - partonFlavour
    - phi
    - pt
    - rawFactor
    - svIdx1
    - svIdx2
  SoftJet:
    - PNetRegPtRawCorr
    - PNetRegPtRawCorrNeutrino
    - PNetRegPtRawRes
    - area
    - btagDeepFlavB
    - btagDeepFlavCvB
    - btagDeepFlavCvL
    - btagDeepFlavQG
    - btagPNetB
    - btagPNetCvB
    - btagPNetCvL
    - btagPNetCvNotB
    - btagPNetQvG
    - btagPNetTauVJet
    - chEmEF
    - chHEF
    - chMultiplicity
    - electronIdx1
    - electronIdx2
    - eta
    - genJetIdx
    - hadronFlavour
    - hfEmEF
    - hfHEF
    - hfadjacentEtaStripsSize
    - hfcentralEtaStripSize
    - hfsigmaEtaEta
    - hfsigmaPhiPhi
    - idx
    - jetId
    - mass
    - muEF
    - muonIdx1
    - muonIdx2
    - muonSubtrFactor
    - nConstituents
    - nElectrons
    - nMuons
    - nSVs
    - neEmEF
    - neHEF
    - neMultiplicity
    - partonFlavour
    - phi
    - pt
    - rawFactor
    - svIdx1
    - svIdx2
    - Et
    - HtCh_fraction
    - HtHF_fraction
    - HtNe_fraction
    - energy
  VBFJet:
    - eta
    - pt
  VBFJetPair:
    - m_jj
    - delta_eta_jj
  MuJet:
    - R_pt
    - minDeltaEta
    - minDeltaEtaSigned
    - minDeltaPhi
    - Zepperfield_Var
    - pt_centrality
  MuPair:
    - dR_mumu
    - m_mumu
    - eta_mumu
    - cosTheta_CS
    - phi_mumu
    - pt_mumu
    - y_mumu
    - phi_CS
  Global:
    ### evt info ###
    - entryIndex # will be FullEvtId
    - luminosityBlock
    # - is_valid
    - isData
    - HasVBF
    - event
    - period
    - run
    - sample_name
    - sample_type
    ### categories ###
    - baseline
    - baseline_Zmumu
    - ggH
    - ggH_Zmumu
    - ggH_Zmumu_JetVeto
    - VBF
    - VBF_JetVeto
    - VBF_Zmumu
    - VBF_Zmumu_JetVeto
    ### regions ###
    - DYEnriched
    ### sign ###
    - OS
    ### jet multiplicity ###
    - N_softJet
    - nJet
    - nSelectedJet
    ### trg info ###
    - HLT_singleMu
    ### global event weight ###
    - weight_EWKCorr_VptCentral
    - weight_EWKCorr_ewcorrCentral
    - weight_MC_Lumi_pu
    ### vertices info ###
    # - PV_npvs
    # - Pileup_nTrueInt
    ### MET info ### --> not used
    # - DeepMETResolutionTune_phi
    # - DeepMETResolutionTune_pt
    # - DeepMETResponseTune_phi
    # - DeepMETResponseTune_pt
    # - PuppiMET_phi
    # - PuppiMET_pt

processes:
- batch_size: 377
  batch_start: 0
  class_value: 1
  datasets:
  - /eos/user/v/vdamante/H_mumu/anaTuples/Run3_2022EE_Hmumu_v2/Run3_2022EE/TTto2L2Nu
  - /eos/user/v/vdamante/H_mumu/anaTuples/Run3_2022EE_Hmumu_v2/Run3_2022EE/TTto2L2Nu_ext1
  nBatches: 43284
- batch_size: 0
  batch_start: 377
  class_value: 1
  datasets:
  - /eos/user/v/vdamante/H_mumu/anaTuples/Run3_2022EE_Hmumu_v2/Run3_2022EE/TTto4Q
  - /eos/user/v/vdamante/H_mumu/anaTuples/Run3_2022EE_Hmumu_v2/Run3_2022EE/TTto4Q_ext1
  nBatches: 0
- batch_size: 23
  batch_start: 377
  class_value: 1
  datasets:
  - /eos/user/v/vdamante/H_mumu/anaTuples/Run3_2022EE_Hmumu_v2/Run3_2022EE/TTtoLNu2Q
  - /eos/user/v/vdamante/H_mumu/anaTuples/Run3_2022EE_Hmumu_v2/Run3_2022EE/TTtoLNu2Q_ext1
  nBatches: 5208
- batch_size: 100
  batch_start: 400
  class_value: 0
  datasets:
  - /eos/user/v/vdamante/H_mumu/anaTuples/Run3_2022EE_Hmumu_v2/Run3_2022EE/GluGluHto2Mu
  # - /afs/cern.ch/work/d/daebi/diHiggs/HH_bbWW/Studies/DNN/DNN_dataset_2024-09-13-13-56-15/GluGlutoRadiontoHHto2B2Vto2B2L2Nu_Combined
  nBatches: 100 #3956