meta_data:
  batch_dict: # here go samples for training
    batch_size: 12970
    nBatches: 1000
  # iterate_cut: (lep1_type >= 0) & (lep2_type >= 0) & (event%4 == 0)
  global_config: /afs/cern.ch/user/a/ayeagle/H_mumu/config/global.yaml
  general_config: /afs/cern.ch/user/a/ayeagle/H_mumu/Studies/DNN/ds_setup/general.yaml
  temp_folder: /eos/user/a/ayeagle/H_mumu/temp_files/
  output_folder: /eos/user/a/ayeagle/H_mumu/root_files/run_2_v2/
  output_name: TTto2L2Nu.root

processes:
- batch_size: 12961
  batch_start: 0
  datasets:
  - /eos/user/v/vdamante/H_mumu/anaTuples/Run3_2022EE_Hmumu_v2/Run3_2022EE/TTto2L2Nu
  - /eos/user/v/vdamante/H_mumu/anaTuples/Run3_2022EE_Hmumu_v2/Run3_2022EE/TTto2L2Nu_ext1
#- batch_size: 1086
#  batch_start: 0
#  datasets:
#  - /eos/user/v/vdamante/H_mumu/anaTuples/Run3_2022EE_Hmumu_v2/Run3_2022EE/TTtoLNu2Q
#  - /eos/user/v/vdamante/H_mumu/anaTuples/Run3_2022EE_Hmumu_v2/Run3_2022EE/TTtoLNu2Q_ext1
#- batch_size: 14790
#  batch_start: 0
#  datasets:
#  - /eos/user/v/vdamante/H_mumu/anaTuples/Run3_2022EE_Hmumu_v2/Run3_2022EE/DYto2L_M_50_amcatnloFXFX
#- batch_size: 2969
#  batch_start: 0
#  datasets:
#  - /eos/user/v/vdamante/H_mumu/anaTuples/Run3_2022EE_Hmumu_v2/Run3_2022EE/ZZto2L2Nu_powheg
#- batch_size: 248
#  batch_start: 0
#  datasets:
#  - /eos/user/v/vdamante/H_mumu/anaTuples/Run3_2022EE_Hmumu_v2/Run3_2022EE/GluGluHto2Mu
#- batch_size: 866
#  batch_start: 0
#  datasets:
#  - /eos/user/v/vdamante/H_mumu/anaTuples/Run3_2022EE_Hmumu_v2/Run3_2022EE/VBFHto2Mu
